apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-autosynconly
  namespace: argocd
spec:
  destination:
    namespace: guestbook-auto-sync-only
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: master
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true