apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-2
  namespace: argocd
spec:
  description: Demo Project 2
  sourceRepos:
    - '*'
  destinations:
    - namespace: ns-1
      server: https://kubernetes.default.svc  # local kubernetes cluster
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
