apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-with-role
  namespace: argocd
spec:
  description: Demo Project 3
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: ci-role
      description: Only allow Sync privileges for project-with-role
      policies:
        - p, proj:project-with-role:ci-role, applications, sync, project-with-role/*, allow
